events {}

http {
    upstream journalapp {
        server journalapp1:8080;
        server journalapp2:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://journalapp;
        }
    }
}